# TensorFlow fundamental exercises

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [16]:
import tensorflow as tf

In [17]:
# Create scalar, vector and matrix
scalar = tf.constant(7)
vector  = tf.constant([10, 7])
matrix = tf.constant([[10, 7],
                      [7, 10]])
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
print(f"Scalar: {scalar}\n")
print(f"Vector: {vector}\n")
print(f"Matrix: {matrix}\n")
print(f"Tensor: {tensor}")

Scalar: 7

Vector: [10  7]

Matrix: [[10  7]
 [ 7 10]]

Tensor: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


### 2. Find shape, rank and size of the tensors you've created in first task.

In [22]:
print("Vector properties:")
print(f"Shape: {vector.shape}\nRank: {vector.ndim}\nSize: {tf.size(vector)}\n\n")

print("Matrix properties:")
print(f"Shape: {matrix.shape}\nRank: {matrix.ndim}\nSize: {tf.size(matrix)}\n\n")

print("Tensor properties:")
print(f"Shape: {tensor.shape}\nRank: {tensor.ndim}\nSize: {tf.size(tensor)}")

Vector properties:
Shape: (2,)
Rank: 1
Size: 2


Matrix properties:
Shape: (2, 2)
Rank: 2
Size: 4


Tensor properties:
Shape: (3, 2, 3)
Rank: 3
Size: 18


### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [20]:
tensor_1 = tf.random.Generator.from_seed(42)
tensor_1 = tensor_1.normal(shape=(5, 300))

tensor_2 = tf.random.Generator.from_seed(24)
tensor_2 = tensor_2.normal(shape=(5, 300))

tensor_1.shape == tensor_2.shape

True

### 4. Multiply two tensors created in task 3 using matrix multiplication

In [26]:
# Tensor_2 has to be reshaped since the dimensions do not match
# [5, 300] @ [5, 300] cannot be multiplicated since inned dimensions do not match
tensor_1 @ tf.reshape(tensor_2, shape=(300, 5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-22.881008  , -30.011253  , -24.556492  ,  -0.93771076,
          3.556963  ],
       [ 28.58917   ,   7.4710608 , -53.60493   ,  -2.274456  ,
        -38.45954   ],
       [  1.4110718 , -21.536648  ,  10.29104   ,   1.2252169 ,
        -11.753285  ],
       [ 27.527142  ,  -2.5605578 ,  19.220512  , -27.467627  ,
          1.3053999 ],
       [ 34.21511   ,  19.059679  ,   2.2713318 ,   8.113086  ,
         10.515867  ]], dtype=float32)>

### 5. Multiply two tensors from task 3 using dot product

In [32]:
result_1 = tf.tensordot(tf.transpose(tensor_1),
             			tensor_2, axes=1)

In [33]:
result_2 = tf.matmul(tensor_1,
					tensor_2,
					transpose_a=True)

In [34]:
result_1 == result_2

<tf.Tensor: shape=(300, 300), dtype=bool, numpy=
array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])>

### 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [35]:
tensor_3d = tf.random.Generator.from_seed(42)
tensor_3d = tensor_3d.normal(shape=(224, 224, 3))
tensor_3d.shape

TensorShape([224, 224, 3])

### 7. Find the *min* and *max* values of tensor created in task 6.

In [38]:
min = tf.reduce_min(tensor_3d, axis=0)
max = tf.reduce_max(tensor_3d, axis=0)
print(f"Minimum: {min}\n")
print(f"Maximim: {max}")

Minimum: [[-2.996973  -2.5635867 -2.4608796]
 [-2.5594032 -2.497232  -2.6856256]
 [-2.0767162 -2.9110887 -2.486153 ]
 [-2.262553  -2.8852544 -2.59792  ]
 [-2.4218671 -2.9944434 -2.554343 ]
 [-2.4936357 -2.416894  -3.4327428]
 [-2.6066418 -2.7672398 -2.8699737]
 [-3.5261705 -2.2359955 -2.6654415]
 [-2.08371   -3.0558362 -2.8776596]
 [-2.6366005 -3.783697  -2.7770448]
 [-2.9771254 -2.97629   -2.3921509]
 [-2.5583189 -3.0635452 -3.1357753]
 [-2.741416  -2.9779747 -2.265383 ]
 [-2.771225  -2.567033  -3.2972128]
 [-2.6355205 -3.0768216 -3.3680334]
 [-2.9851797 -2.1347136 -2.3408713]
 [-2.585004  -2.8213434 -2.8839903]
 [-2.2522912 -3.1381915 -2.846771 ]
 [-3.7462046 -2.6484005 -2.3898544]
 [-3.4100366 -2.952386  -3.004585 ]
 [-3.0809257 -2.6478539 -3.0147562]
 [-2.7513595 -2.4115767 -3.1387491]
 [-2.533062  -2.872635  -2.0623527]
 [-3.4444072 -2.9571126 -2.1732686]
 [-2.6114483 -2.6475773 -2.3642206]
 [-3.617893  -2.7603884 -2.7566614]
 [-2.3450315 -2.8423274 -2.6800401]
 [-3.6342864 -2.973

### 8. Create a tensor with random values of shape `[1, 224, 224, 3]`, then squeeze it to change its shape to `[224, 224, 3]`.

In [41]:
tensor_3 = tf.random.uniform(shape=(1, 224, 224, 3))
print(f"Shape after creation: {tensor_3.shape}")

tensor_3 = tf.squeeze(tensor_3)
print(f"Shape after squeezing: {tensor_3.shape}")


Shape after creation: (1, 224, 224, 3)
Shape after squeezing: (224, 224, 3)


### 9. Create a tensor with shape `[10]` using values of your own choice. Then find the index at which to maximum value is.

In [45]:
my_tensor = tf.constant([0, 12, 52, 25, 7, 24, 12, -92, 23, 1])
print(f"Shape: {my_tensor.shape}")
print(f"Max value index: {tf.argmax(my_tensor)}")

Shape: (10,)
Max value index: 2


### 10. One-hot encode the tensor created in task 9.

In [50]:
onehot_tensor = tf.one_hot(my_tensor, depth=tf.reduce_max(my_tensor))
print(f"One-hot tensor shape: {onehot_tensor.shape}")
print(f"One-hot tensor itself: {onehot_tensor}")

One-hot tensor shape: (10, 52)
One-hot tensor itself: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0